language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm run build

after_success:
  - tar -czf dist.tgz dist
  - export SSHPASS=$DEPLOY_PASSWD
  - sshpass -e scp -o StrictHostKeyChecking=no dist.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

addons:
  apt:
    packages:
      - sshpass

env:
  global:
  - secure: WAsxiNQszKCa2WnPvZkgrSE5nZr7dq/pztwb8SQwYuN7xyVyWVow2Qldh5XaUA/N+mum5I1G+ny0+kRNRkIYfW64wbva7RFX9P2wL+QzQXZp8ctBrJA+KFJ9ZU+OqC0kVY6zWMuykWGV6H/9zSOUWovTAb1KhuwI8AhI4eSKl++sgHimueZ024Du/9vMOuMfclBrj9pFWTnh6ptrNlMcoD2hQ9bnKLGeANbBrbq7IxHVNoKbPj3czG8hs88GlE8nekDUdWXTgWiS9BELZhHNr4v/ATG0AupbJVrKDB9fkz5X/P+AAoFT46FR4Zm6w9XDf/q2ZDkt/2GwSdqTLPEZtJX4R84zL3SoKfwVdA0fw41w5KMX5H6lnFHKP0UjpsGQyL2zOs71/XG8GFBpLQIOLpamkyll4+QaRCcRKmC6IjndvJwbQ6iw5n6cfkCpVnAysYhVJ71VEfm0XZNk0mghE1lprQUYIAnOBexh/eNcHfIgKNf94phBakqHTuksgAvACS9h1nA9o2qznYUu3E7EM99g2DOI8O0KgGwZJCZJ5HTt5N2XDmKBM/zHnXoVU/5JPkDTSiyuB8isEtjRbCmYrtce+d65aEIX2NTiOSsinMwABKxmMCqGan3TcG/7oq1OJIei6e4rpnyZPzglhQcmZMZm7mmH/zF0xVwq9cVM5KE=
  - secure: ukSagdnho5bkXTDh+ZrN+H7/BnGCUlZrTX9i6aiVqxaZqEC4wWGAWeqTbKOGD66/HLTuTVq3AyIIBlsPDlwrmzi/163XnfBg0xsdBlty7wK32RNfp+acK17SV2yGJS4avLlT98Nkx3t+gQxaCwsb6PfLheo0Q8vodg57JzE6Z/cC6B+qyOqCKTtNfWRSj37jlZ2Xvca3vJ1E5CSStKq9OKTnqgodLI7ZqRhdHoDM3d4mQjKKzwKdddGgRWteKj20rvUVLQlD17RrqzZPfb3WjiMbtsNsVyL6J3OlzL7T/mxznY/CibY11mSM5sBUv0IyJtHz//3fw2V3pibSVe5OpNU1YFJF0GFzcW5xNwovReC762rJYJsF0atflSS49Kw9TabJJYx1iWuf+HkEvBnSeVkGHaZERgrZBSPNVbCy5+0F/GBoNLcU7wmMIL+N5RTiYweOpqSMAjom0VJIEpIS2Fs/yRY+RT8p1q6JoVXM6CkiTOyblqT4oe822Qk/VEMl6HYOouN1LTUi/8OGCAJ1BqA3asLlJPOKT0O7P4LM0oJwk1IkWWrOJPoYszB7NQ9fldrvnZl1lJSHcBpM4BwRc1Qjps0qgicDwXeMs9Ea/uKhx1vQTykfNu9CSXgPJugOSMPgpej7hgJPfL4Ym6teCjZ/h+Zzq18WBZWUjN1JAyc=
  - secure: RuFZKWUISZLMTE8eaHZU+Xw/M5dJHqqXXYBnkDdacDZ3Bhzm6jZ4BTX7XYl2kN8n1TKOkBMQf8ZaZjZ+LgodviXMTscGpS/ehi3YObFmcJrrTgKE8fCXKdJwl67ZY0fPs+4jK5Xv76Jtu++OjSFxHbbw7JwTYn11cqFKeJd1js9jgybjBgXRQpZwFPVzIB/LNaW8hErjWAzDq0T+IGpaYvmzTmS5iFxhi8qjOFgeziJ/EQTUK7RhuCqjwWY8TU6tyrIx/OiqcI2kbt1bVJdHbKFabBQ2iWTn0ZQjeP2Ng2YRDHieh0ViqyuXOGG3DBMAjLClOxdaXLtg/kDjLlhd+y1CjVJqnxcR0N7+QPAM46+XvKGrr3bWaSg/ox4MFRxpn29P7W9h+3XNFu5DUHe5++iPQFZPHFdBvX4Vf7vhl0yyafiNRyo3BrIcfuFqJM03e2n8jJS12tEeYVLx7ls6uMM0yXhLasPa66uns40sYM5b2ZgryK8ud2IruhfjTBCtE5FRGOBAzzROcx6fTMESd+8j4XaoHVWrJGwNmskeK+N/4BbzRXEtLNU3P7seDW1hebuTIN/ezxQTr0wnUMhE2VbWP9SlTM5dZelzHKUEV2qckyAor31tHQYvRZtG6VEk2knO5sQFigrD6IvrpPPPNphk9phUSemLRRZPYZxwSWo=
  - secure: UUauk5D6ORKBeM+cWC6/9xhFr00LLJJ9an3dYUwXe0uw/mqEYS1uQWE823msT1dFpcUHEle/dk6qjOi/O+weFJbUi+it/ZnL5R49Zxx5fdML0VvE3vU0JL/Z/epW2jAyQL/6wjAE0OOrjchymZJvZXT8oolWQ4cyuVTiVSRu7V7q4n09tvBpOVZ+Kz4amh7XOuiCKHJBGuDbe17yhYY9qGJ4ZEV+bLDpzmLsuIh6Bsk7IOiSW3sJogg710mXzpUB6vZdybMZmGu3AVGDelFCW78dcCeOnxrdY3kk+0sw26gbAazW5tSZUNTfIHsZ+IQ51YhO17QdDeNloC16YkLRcvxKnIGD94iv/saW31JSV4tRchgTrxn3R8598i9nhFeFtlbYXC2nf/k3V+XI8Op0bzYXVmk8quGGHg0zG/d4RpsgqMKfZW8givl5q3GfncMkoKjlmi/MFBvh4lMpE/cK1vJnl5PfsdjdAFxKcqGS4ijYWwQmAz8rZoJF08ylXwTwNUyZxsEg+CwJCxAhrGiC0awMQEr+6Ijks3e+IzTsUKcxxtsH7fbkCCeJ7I1jpUYJaKU19RDEGvzWNckxr1E9QAYDyZegxnf8CVZDxzXmPKfSqw5dQW8KEfqoh2t8G/zDxdEmLjnKMOVZn4wULXuxX0eamZdMbQ4xr+cnK2iOwQE=
