language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm run build

after_success:
  - tar -czf dist.tgz dist
  - export SSHPASS=$DEPLOY_PASSWD
  - sshpass -e scp -o StrictHostKeyChecking=no dist.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

addons:
  apt:
    packages:
      - sshpass

env:
  global:
  # Secured variables : DEPLOY_HOST, DEPLOY_PATH, DEPLOY_USER, DEPLOY_PASSWD
  - secure: bOM+Xk+jQ/CXfj88S/L1HayV8MvBWF5iZa3UetRcc2l65GCo/rTDMc31xP+RIuKRy8p4vhRA0aWQ3L/CqCy2NUOpItlVUWWwtdewQq5X25/9O+Dg+MMIvKbqKq0sIjIjqbklhZy0drcFNFKzVnWg9qjo21SMkq97vlPuEBs9OgDfoecmBiTr7qV72yAlyT+J1TIZFsfx4MXMB6a53TuYnCvordwgaeHysu+dE4xRosDW3vab8+7IlUZcNz7VBCYiVQJf0Oj5DhnDgjvOn8Oo4CO2JyU4HgCxDQAykse1WMGczY7sebWxZ8j0KCAZstb9rHRxMkD6aR0CVN/VrW/E8TSgMamMwnxPU5/9eEo6Os3SpMJWAu5JTZdolcWEuAq7mD5T4IoBLMsvbmdUWGFTqKJ79ZZ3t5S8CHcEZbD4sfmY/sCF+v/h5MbJXBvwJKS9dyvRnyCplW3vT8LGWDKg4CLsX5xBLdkBos4zcw+8XKfxuyBIyTHCELH5+t6NYs7Z6uceU1DGRVUy5alWYqmr54CP6RjMlq/ppkO/aLYpgRY22p0ffR46p5wkMfvpbSKD3xtxv/LlKmn64pG5KSAjxcg9mDqEpS/+kn/U7EC4+9tpuZ/3SBBvH70PNFIhh5bwlhBxnHDBk3hGF36/X9nCbuabTQF0x/IEweAgeslL4a0=
  - secure: TTFfkn+KPtTpfxhld4YejoUpaDhu+gBuQWLzt2rinSbYLKBkPBVy2G4wQyLXQ3swe83CXxcKYsNa5mxSc3CA2Q+TgXf3G59tfbLZpg1i4imyR1Ded6Cu9277WOYGKrhoJUYWMpUfxweeDtljWJHnX6NsmhooO80QmFm4759TTLsOL/BVgbdxBIZLIBIumIH2XzO9GQf75wUZKsVVgYIf+imoTRKXLsLI+DZHjN7QreOzPwqNUUetNVvSp9f4npjOYaeFyJI70obGQdPu3YCerGWT4/Q9YCDnId8VgEBMEF6DbZSXdraXtKlL/hWAIlEHiXnGWyA4tbMjCw9/uzOhhC5SDxDkQp3vQ7FJibKaLOl9e/PcxQYQK68vIs+rbBn6HaZw+HmvimQIRwRPmTA3uEOEpfan093NYI2/eUbXPu1gMKfsY74/Ud1CCe0Vjul44eeFkR9l04OVpAsOwOxhqB4DmMGruHle25n8lRt386SI7BdfqYSriD38P4Ay7QfzktPm9NnnRQzZ0PzoXd5i1D5XC7EeyOznkBbl6EVJ+9D5lWst2Ls8MwHbeS0KnbLCUwfHJiV1Mz06P9kSbNMJxb7OhgEFRuz/1Zx8Rw392ufPFZ+gs1aXm3Qw7660FZDkKXPhinDCb8p/sNjTvBiTmNwKm1W5j1zinAyh1D0Vyz4=
  - secure: I294az1dzWd092hnRaW525SZDTs11VqNpcwPhu6LBZaOqii7fBbk9HFsQAtciMTxKYjlUxvu0rceX0GpVxJPpMQXUd1+Ve2cBmFzBfTWNZCWS4xi+zFP+j5vdrmRicNE78ysaunCGstmWxNvpD5ZVq86e1IjK2PNihUDBngeORUwkHeKEla5cH5iENhQ4DP60+cLOjW+ti5l+Zmgt+TCNYz7vXaZcAC/weWWz7cWlRFjYlvgi7izhJkMXbQEEOR1ttB5Uqpl5pRugo5lTNfV4ZQa7tmaHQ97bcuyWwpEl9b+coen9/fUIuDX7MSrw0cHSqnjaz4DRIiTC2HzmP6yuoQp/tiDBmU/0c+SUtsP9QuvOssrEaOCUzHOk7F2Hr8fsPEiHrMvR6VY6gj8NbFVp5cG+F8vQH4576cxpIj89zegIBUf2/6mpasRziHo/FAsevgZph3JjIDQ4sBVdtc1hHCOA0MaXBPkhQSmiuEqxItcBTP02tNeFFAp7W0Z+tnareF00wN7Zk9HkaPZFPnQ0Xb1mOFb8Mi+XM17aJ/pEDN63E94DiOw8YVNB2KfVmDV2o+1FsA4muWuTT0ZwJA3J7ZSbnJD6qb38CAlirYy+qKEly8s5bY1m5Hk/PNE3uv7oQtt9qQkuvn8Uh509trX4fFZfoj1jMwib1mK4DtIGm8=
  - secure: DCptc6m2mqTlpUqPj4Wm7ofcHHc5xWzKiFzM711KHPVqVbMjYmE6kJMZT+YS2Vkqh5S26KnYNwNH8RjwGlGVRd6BTFe1HL++dzwTHbWm2W6UjUQyKULosql9P0e12ZhrAlWvl9bLg6cdzgn+4dvUCib5aNbJT3025opFiNhUtWWaH5P5IdRshA+MbrmZITZdNzrm/1Dm/wnU0UQX3KI+Ig0uU5sCRyQSr5UMIdehK+7ncCpbpyMOVuj/fptqsOCpHBH1JIlGVUlfcdIFOLtLIvEZ2x6NUu8HXtXfmetEgVnbmel10HEvmRrxCHCXEvYKiBpAVhsH1HoMgu6CqsX+TQwqc0tweRVcIUx2XE2GcPX1EVUZTez9ZtoaTB3Ia3y1twnucG6w04YZGpULL/4dTq0dloFrUkzC0fjvFgveA1N3PVdetXAjofWJ1gy1iKxkrnmmjPhAjpMSDPIpIW8QbtScL91XaKu+bcP0+3WsU0OWaNGmaIA5kc+AQD0fZHe/rFFttTRre8xbnMzaLbSvEAwkD/UxYAroVFfgpGmpLosN0nsbtlDBX15H9AYLFp2FQrKCjrPjUvJKo3HvZWt/cmgwnUrl8Pr4AG3+qQ1iwf7tTbPtvOWw1M60y7ApOnLXvcvNXDxwldARdUFKOvItVc+ZSEt6cz+NRtjV6jGixJY=
