export const MENU_TOGGLE = 'MENU_TOGGLE'

export const APP_LOADING = 'APP_LOADING'
export const APP_LOADING_FINISHED = 'APP_LOADING_FINISHED'

export const RECIEVE_GAMES = 'RECIEVE_GAMES'
export const RECIEVE_GAME_DETAILS = 'RECIEVE_GAME_DETAILS'

export const RECIEVE_GAME_CATEGORIES = 'RECIEVE_GAME_CATEGORIES'
